# Generated by Django 3.0.7 on 2021-05-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('accounttypeid', models.AutoField(primary_key=True, serialize=False)),
                ('accounttypename', models.CharField(blank=True, max_length=250, null=True)),
                ('shortname', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'AccountType',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(blank=True, max_length=250, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('accounttypeid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.AccountType')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Account',
                'managed': True,
            },
        ),
    ]
